// Text-macro replacements. Runs after the formatter and applies user-defined
// trigger -> expansion substitutions to the transcript.
//
// Each entry is processed in registration order; chained replacements are
// intentional (a later entry can replace text generated by an earlier one),
// but each entry is applied at most once per pass over the current string,
// so a self-referential trigger cannot recurse infinitely.

import type { PostProcessContext, PostProcessor } from '@main/postprocess/pipeline';
import type { ReplacementEntry } from '@shared/types';

const REGEX_SPECIAL_CHARS = /[.*+?^${}()|[\]\\]/g;

/**
 * Treat ASCII alphanumerics, underscore, and CJK / kana code blocks as
 * "word" characters. JavaScript's built-in `\b` does not recognise non-ASCII
 * scripts, so we evaluate boundaries ourselves.
 *
 * - `぀-ヿ` covers Hiragana (U+3040–U+309F) and Katakana (U+30A0–U+30FF).
 * - `一-鿿` covers the CJK Unified Ideographs block (U+4E00–U+9FFF).
 */
function isWordChar(c: string): boolean {
  if (c.length === 0) return false;
  return /[A-Za-z0-9_぀-ヿ一-鿿]/.test(c);
}

function escapeRegex(s: string): string {
  return s.replace(REGEX_SPECIAL_CHARS, '\\$&');
}

/**
 * Replace every occurrence of `trigger` in `text` with `expansion`. When
 * `wordBoundary` is true, surrounding characters must be non-word (or the
 * string boundary) for a match to take effect.
 */
function applyEntry(text: string, entry: Readonly<ReplacementEntry>): string {
  if (entry.trigger.length === 0) return text;
  const pattern = new RegExp(escapeRegex(entry.trigger), 'g');

  if (!entry.wordBoundary) {
    return text.replace(pattern, () => entry.expansion);
  }

  return text.replace(pattern, (match, offset: number) => {
    const before = offset > 0 ? text.charAt(offset - 1) : '';
    const afterIndex = offset + match.length;
    const after = afterIndex < text.length ? text.charAt(afterIndex) : '';
    const beforeOk = before === '' || !isWordChar(before);
    const afterOk = after === '' || !isWordChar(after);
    return beforeOk && afterOk ? entry.expansion : match;
  });
}

/**
 * Pure helper exposed for unit testing. Applies a list of replacement
 * entries to `text` in order and returns the resulting string.
 */
export function applyReplacements(
  text: string,
  entries: ReadonlyArray<ReplacementEntry>
): string {
  let current = text;
  for (const entry of entries) {
    current = applyEntry(current, entry);
  }
  return current;
}

export const replacementsProcessor: PostProcessor = {
  name: 'replacements',

  async process(text: string, ctx: PostProcessContext): Promise<string> {
    const entries = ctx.settings.replacements;
    if (!entries || entries.length === 0) return text;
    return applyReplacements(text, entries);
  }
};
